set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)

# musl cross-compiler (set MUSL_TOOLCHAIN_PREFIX externally or use default)
if(NOT DEFINED MUSL_TOOLCHAIN_PREFIX)
    set(MUSL_TOOLCHAIN_PREFIX "arm-linux-musleabihf")
endif()

set(CMAKE_C_COMPILER ${MUSL_TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${MUSL_TOOLCHAIN_PREFIX}-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
